### ISSUE TITLE
Mapping between ssl.txt and SSL example in code

### ISSUE THREAD

**Issue by YpsilonZet** [surgitaix/sdclib#12]
Hello,

I wanted to test the sdc examples with own generated certificates.
But now I'm unsure which certificate I should use in which state.

My current understanding is:
ssl.txt <-> ExampleCode
rootCA.pem <-> ca.pem
leafkey.pem <-> sdccert.pem
leaf.pem <-> userkey.pem

Is this correct? 
But then I will get a Poco::FileException with  "File access error" when it comes to this line:
`t_SSLConfig->useKeyFiles("", "leaf.pem", "");`

**Comment by FBaumeister** [comment]
Hello YpsilonZet,
it looks like that in the refactoring process of the Examples we forgot to edit ssl.txt as well.
The last two items need to be swapped:

rootCA.pem <-> ca.pem
**leaf.pem <-> sdccert.pem
leafkey.pem <-> userkey.pem**

The ssl.txt is still a WIP file but we will fix that.
Thank you for reporting that issue!

**Comment by YpsilonZet** [comment]
Thanks, this got it working.
