### ISSUE TITLE
Cmake: Build sdclib and example in one step

### ISSUE THREAD

**Issue by YpsilonZet** [surgitaix/sdclib#13]
Hi,

as far as I understand the current project structure, the sdclib must be accessible as binary if we want to use the CMakeExample.

Do you have any plans to extend it, that the example and the sdclib can be build in one step?

**Comment by FBaumeister** [comment]
Hi,
The CMakeExample itself is not one of 'the' SDC Examples (or Advanced Examples) which can be built along with the SDCLib. So it could as well be placed inside /doc. CMakeLists represents your own "root" CMakeLists where you do your project configuration and gather your dependencies. Here its meant to demonstrate how to call find_package on SDCLib.
With that said, can you further explain your request?
Do you want a CMake target for the SDCLib inside your own CMakeLists. If yes, what are you trying to achieve?
Thank you!

**Comment by YpsilonZet** [comment]
My idea was, instead of using find_package(SDCLib), using add_subdirectory(SDCLib) in a more global repository. So, when I build my app, the SDClib will also be build instead of having the sdclib prebuild and need to find where the library-file was placed.
e.g.: 
![structure](https://user-images.githubusercontent.com/11175251/86741077-6943b280-c037-11ea-98cf-e559a1ad8340.png)

But if I setup the project this way (like in the screenshot and using add_subdirectory instead of find_package), I will get errors in my source files in the app-folder, because of missing references.
I would need to set SDCLib_INCLUDE_DIRS and otherCMake variables, that would normally been set in the FindSDCLib.cmake manually

**Comment by FBaumeister** [comment]
Hi YpsilonZet,
please have a look at my updated README.md at the latest master commit:
https://github.com/surgitaix/sdclib/blob/master/Examples/README.md#cmake-integration
When setting this variable before calling the add_subdirectory(sdclib) command you currently get around these issues.
Does this solve your problem?

**Comment by YpsilonZet** [comment]
Hi,
sorry for the late reply.
Yes, thats working for me.
Can be closed
Thanks
