### ISSUE TITLE
SubscriptionClient produces wrong t_expireString in german Ubuntu

### ISSUE THREAD

**Issue by YpsilonZet** [surgitaix/sdclib#15]
Hi,

we used a german Ubuntu 18.04 LTS version and made a Consumer based on the SDCLib.

We got an error that part of the xml after a discover couldn't be parsed.

We found out that following XML wasn't valid:
`<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<p1:Envelope xmlns:p1="http://www.w3.org/2003/05/soap-envelope" xmlns:dpws="http://docs.oasis-open.org/ws-dd/ns/dpws/2009/01" xmlns:mm="http://standards.ieee.org/downloads/11073/11073-10207-2017/message" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wse="http://schemas.xmlsoap.org/ws/2004/08/eventing">
  <p1:Header>
      <wsa:Action>http://schemas.xmlsoap.org/ws/2004/08/eventing/Subscribe</wsa:Action>
          <wsa:MessageID>urn:uuid:c49f19a2-f693-11ea-8529-000c298ae72d</wsa:MessageID>
              <wsa:To>http://192.168.80.5:40745/BICEPSService</wsa:To>
    </p1:Header>
    <p1:Body>
        <wse:Subscribe>
            <wse:Delivery>
                <wse:NotifyTo>
                    <wsa:Address>http://192.168.80.100:45559/BICEPSService</wsa:Address>
                    <wsa:ReferenceParameters>            
                        <wse:Identifier>c49d4406-f693-11ea-acbf-000c298ae72d</wse:Identifier>
                    </wsa:ReferenceParameters>
                </wse:NotifyTo>
            </wse:Delivery>
            <wse:Expires>PT120,000000S</wse:Expires>
            <wse:Filter Dialect="http://docs.oasis-open.org/ws-dd/ns/dpws/2009/01/Action">http://standards.ieee.org/downloads/11073/11073-20701-2018/StateEventService/EpisodicAlertReport http://standards.ieee.org/downloads/11073/11073-20701-2018/StateEventService/EpisodicMetricReport http://standards.ieee.org/downloads/11073/11073-20701-2018/StateEventService/PeriodicAlertReport http://standards.ieee.org/downloads/11073/11073-20701-2018/StateEventService/PeriodicMetricReport http://standards.ieee.org/downloads/11073/11073-20701-2018/ContextService/EpisodicContextReport http://standards.ieee.org/downloads/11073/11073-20701-2018/ContextService/PeriodicContextReport</wse:Filter>
        </wse:Subscribe> 
    </p1:Body>
</p1:Envelope>`

The run method in the SubscriptionClient.cpp produces a t_expireString with value PT120,000000S but it need to be a dot instead of a comma.

In an english Ubuntu environment everything went fine.

**Comment by FBaumeister** [comment]
Hi YpsilonZet,
thank you for reporting that issue!
Please try the (quick)fix on the develop_baumeister branch.

**Comment by FBaumeister** [comment]
Does that fix solve your issue?

**Comment by YpsilonZet** [comment]
Sorry for late Response.

This works for me
