### ISSUE TITLE
Possibility to set a fixed Unicast Traffic port

### ISSUE THREAD

**Issue by YpsilonZet** [surgitaix/sdclib#16]
Is there currently a possibility to set a specific port for the Unicast traffic instead of using a random assigned port?

I made a test, where I hard-coded the MDPWSPort in NetworkConfig.h, but this seems to work only for a Provider. 
The Consumer with the same sdclib base is still using different ports.

For setting up and testing a firewall this feature would be important

**Comment by FBaumeister** [comment]
Hi YpsilonZet,
thank you for your request.
We are aware of that and currently let the system select a free port.
We have currently no plans to (re)implement the feature of specifiying a portrange in this version of the SDCLib in the near future.
