### ISSUE TITLE
SDC consumer crashes when connection to SDC Provider is lost.

### ISSUE THREAD

**Issue by wai-mun-leica** [surgitaix/sdclib#17]
Hello,

I am running SDCLib on windows and I notice, during debug mode, the consumer throws an iterator related exception when connection to a connected provider is lost.

The call stack points to OSELib::DPWS::SubscriptionClient::run(). It seems accessing an invalidated iterator in the loop of handling expired subscription is causing the problem.

        for(auto& expiredSubscription : recentlyExpiredSubscriptions)
        {
            auto foundIterator = m_subscriptions.find(expiredSubscription);
            if(m_subscriptions.end() != foundIterator)
            {
                m_subscriptions.erase(foundIterator); // invalidates iterator
                invokeUnsubscribe(foundIterator->second, defaultSchemaGrammarProvider);
            }
        }

Perhaps it should be 
               invokeUnsubscribe(foundIterator->second, defaultSchemaGrammarProvider);
                m_subscriptions.erase(foundIterator);

Wai-Mun

**Comment by FBaumeister** [comment]
Hello,
thank you for using the SDCLib and taking the time to report this issue.
Can you checkout the develop_baumeister branch and test, if the behaviour is gone.
If I am not mistasken, your suggested fix should already be included there in one of the latest commits, but it has not yet found its way back into the master branch.
Can you check, if this resolves your issue?
Thank you very much.

Best regards,
Fabian Baumeister

**Comment by wai-mun-leica** [comment]
Hello Fabian,

Thank you for your reply. Yes, I've tested that branch and it solves this issue.

Best regards,
Wai Mun
