### ISSUE TITLE
FindSDCLib.cmake not up-to-date

### ISSUE THREAD

**Issue by lukas-bernhard** [surgitaix/sdclib#2]
Currently it is not possible to build using FindSDCLib.cmake due to out-dated include paths containing "OSCLib". I know it's WIP, but a fix would be much appreciated :).

**Comment by FBaumeister** [comment]
Hello,
thank you for reporting this issue!

You can pull version 4.0.2 which should fix FindSDCLib.cmake. Other remainings of OSCLib got removed too.
Furthermore the member functions of ServiceManager discoverOSCP() and async_discoverOSCP() were renamed to discover() and async_discover. (The old ones are kept to not break legacy code but marked deprecated and will be removed in future versions).

It would be great if you can confirm that everything works as expected again.

Thank you!

**Comment by lukas-bernhard** [comment]
Thank you for the quick response! Now everything works as expected.

Best,
Lukas
