### ISSUE TITLE
Could not build sdcLIB V4.3.5 and V4.3.4

### ISSUE THREAD

**Issue by dmeise** [surgitaix/sdclib#4]
Hello,
I tried to build the newest sdcLIB versions and got some errors when building SDCConsumerAdapter.cpp. I used "CMake" and then "make install"

user@debian:~/sdclib_build_debug$ make install
[  3%] Built target DataModel
[ 34%] Built target Foundation
[ 39%] Built target Util
[ 56%] Built target Net
[ 59%] Built target Crypto
[ 63%] Built target NetSSL
Scanning dependencies of target SDCLib
[ 64%] Building CXX object src/CMakeFiles/SDCLib.dir/SDCLib/SDCLibrary.cpp.o
[ 64%] Building CXX object src/CMakeFiles/SDCLib.dir/SDCLib/SDCInstance.cpp.o
[ 64%] Building CXX object src/CMakeFiles/SDCLib.dir/SDCLib/Config/SDCConfig.cpp.o
[ 64%] Building CXX object src/CMakeFiles/SDCLib.dir/SDCLib/Config/NetworkConfig.cpp.o
[ 64%] Building CXX object src/CMakeFiles/SDCLib.dir/SDCLib/Config/SSLConfig.cpp.o
[ 64%] Building CXX object src/CMakeFiles/SDCLib.dir/SDCLib/Data/SDC/FutureInvocationState.cpp.o
[ 64%] Building CXX object src/CMakeFiles/SDCLib.dir/SDCLib/Data/SDC/SDCConsumer.cpp.o
[ 64%] Building CXX object src/CMakeFiles/SDCLib.dir/SDCLib/Data/SDC/SDCConsumerOperationInvokedHandler.cpp.o
[ 64%] Building CXX object src/CMakeFiles/SDCLib.dir/SDCLib/Data/SDC/SDCProvider.cpp.o
[ 65%] Building CXX object src/CMakeFiles/SDCLib.dir/SDCLib/Data/SDC/SDCProviderStateHandler.cpp.o
[ 65%] Building CXX object src/CMakeFiles/SDCLib.dir/SDCLib/Data/SDC/SDCConsumerAdapter.cpp.o
/home/user/sdclib/src/SDCLib/Data/SDC/SDCConsumerAdapter.cpp:516:121: error: specialization of ‘template<class RequestType> Poco::URI SDCLib::Data::SDC::SDCConsumerAdapter::getRequestURIFromDeviceDescription(const RequestType&) const’ in different namespace [-fpermissive]
 Poco::URI SDCConsumerAdapter::getRequestURIFromDeviceDescription(const OSELib::SDC::GetMDDescriptionTraits::Request & ) const {
                                                                                                                         ^~~~~
In file included from /home/user/sdclib/src/SDCLib/Data/SDC/SDCConsumerAdapter.cpp:8:0:
/home/user/sdclib/include/SDCLib/Data/SDC/SDCConsumerAdapter.h:70:12: error:   from definition of ‘template<class RequestType> Poco::URI SDCLib::Data::SDC::SDCConsumerAdapter::getRequestURIFromDeviceDescription(const RequestType&) const’ [-fpermissive]
  Poco::URI getRequestURIFromDeviceDescription(const RequestType & request) const;
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/sdclib/src/SDCLib/Data/SDC/SDCConsumerAdapter.cpp:521:112: error: specialization of ‘template<class RequestType> Poco::URI SDCLib::Data::SDC::SDCConsumerAdapter::getRequestURIFromDeviceDescription(const RequestType&) const’ in different namespace [-fpermissive]
 Poco::URI SDCConsumerAdapter::getRequestURIFromDeviceDescription(const OSELib::SDC::GetMDIBTraits::Request & ) const {
                                                                                                                ^~~~~
In file included from /home/user/sdclib/src/SDCLib/Data/SDC/SDCConsumerAdapter.cpp:8:0:
/home/user/sdclib/include/SDCLib/Data/SDC/SDCConsumerAdapter.h:70:12: error:   from definition of ‘template<class RequestType> Poco::URI SDCLib::Data::SDC::SDCConsumerAdapter::getRequestURIFromDeviceDescription(const RequestType&) const’ [-fpermissive]
  Poco::URI getRequestURIFromDeviceDescription(const RequestType & request) const;
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/sdclib/src/SDCLib/Data/SDC/SDCConsumerAdapter.cpp:526:115: error: specialization of ‘template<class RequestType> Poco::URI SDCLib::Data::SDC::SDCConsumerAdapter::getRequestURIFromDeviceDescription(const RequestType&) const’ in different namespace [-fpermissive]
 Poco::URI SDCConsumerAdapter::getRequestURIFromDeviceDescription(const OSELib::SDC::GetMdStateTraits::Request & ) const {
                                                                                                                   ^~~~~
In file included from /home/user/sdclib/src/SDCLib/Data/SDC/SDCConsumerAdapter.cpp:8:0:
/home/user/sdclib/include/SDCLib/Data/SDC/SDCConsumerAdapter.h:70:12: error:   from definition of ‘template<class RequestType> Poco::URI SDCLib::Data::SDC::SDCConsumerAdapter::getRequestURIFromDeviceDescription(const RequestType&) const’ [-fpermissive]
  Poco::URI getRequestURIFromDeviceDescription(const RequestType & request) const;
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/sdclib/src/SDCLib/Data/SDC/SDCConsumerAdapter.cpp:531:113: error: specialization of ‘template<class RequestType> Poco::URI SDCLib::Data::SDC::SDCConsumerAdapter::getRequestURIFromDeviceDescription(const RequestType&) const’ in different namespace [-fpermissive]
 Poco::URI SDCConsumerAdapter::getRequestURIFromDeviceDescription(const OSELib::SDC::ActivateTraits::Request & ) const {
                                                                                                                 ^~~~~
In file included from /home/user/sdclib/src/SDCLib/Data/SDC/SDCConsumerAdapter.cpp:8:0:
/home/user/sdclib/include/SDCLib/Data/SDC/SDCConsumerAdapter.h:70:12: error:   from definition of ‘template<class RequestType> Poco::URI SDCLib::Data::SDC::SDCConsumerAdapter::getRequestURIFromDeviceDescription(const RequestType&) const’ [-fpermissive]
  Poco::URI getRequestURIFromDeviceDescription(const RequestType & request) const;
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/sdclib/src/SDCLib/Data/SDC/SDCConsumerAdapter.cpp:536:118: error: specialization of ‘template<class RequestType> Poco::URI SDCLib::Data::SDC::SDCConsumerAdapter::getRequestURIFromDeviceDescription(const RequestType&) const’ in different namespace [-fpermissive]
 Poco::URI SDCConsumerAdapter::getRequestURIFromDeviceDescription(const OSELib::SDC::SetAlertStateTraits::Request & ) const {
                                                                                                                      ^~~~~
In file included from /home/user/sdclib/src/SDCLib/Data/SDC/SDCConsumerAdapter.cpp:8:0:
/home/user/sdclib/include/SDCLib/Data/SDC/SDCConsumerAdapter.h:70:12: error:   from definition of ‘template<class RequestType> Poco::URI SDCLib::Data::SDC::SDCConsumerAdapter::getRequestURIFromDeviceDescription(const RequestType&) const’ [-fpermissive]
  Poco::URI getRequestURIFromDeviceDescription(const RequestType & request) const;
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/sdclib/src/SDCLib/Data/SDC/SDCConsumerAdapter.cpp:541:114: error: specialization of ‘template<class RequestType> Poco::URI SDCLib::Data::SDC::SDCConsumerAdapter::getRequestURIFromDeviceDescription(const RequestType&) const’ in different namespace [-fpermissive]
 Poco::URI SDCConsumerAdapter::getRequestURIFromDeviceDescription(const OSELib::SDC::SetStringTraits::Request & ) const {
                                                                                                                  ^~~~~
In file included from /home/user/sdclib/src/SDCLib/Data/SDC/SDCConsumerAdapter.cpp:8:0:
/home/user/sdclib/include/SDCLib/Data/SDC/SDCConsumerAdapter.h:70:12: error:   from definition of ‘template<class RequestType> Poco::URI SDCLib::Data::SDC::SDCConsumerAdapter::getRequestURIFromDeviceDescription(const RequestType&) const’ [-fpermissive]
  Poco::URI getRequestURIFromDeviceDescription(const RequestType & request) const;
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/sdclib/src/SDCLib/Data/SDC/SDCConsumerAdapter.cpp:546:113: error: specialization of ‘template<class RequestType> Poco::URI SDCLib::Data::SDC::SDCConsumerAdapter::getRequestURIFromDeviceDescription(const RequestType&) const’ in different namespace [-fpermissive]
 Poco::URI SDCConsumerAdapter::getRequestURIFromDeviceDescription(const OSELib::SDC::SetValueTraits::Request & ) const {
                                                                                                                 ^~~~~
In file included from /home/user/sdclib/src/SDCLib/Data/SDC/SDCConsumerAdapter.cpp:8:0:
/home/user/sdclib/include/SDCLib/Data/SDC/SDCConsumerAdapter.h:70:12: error:   from definition of ‘template<class RequestType> Poco::URI SDCLib::Data::SDC::SDCConsumerAdapter::getRequestURIFromDeviceDescription(const RequestType&) const’ [-fpermissive]
  Poco::URI getRequestURIFromDeviceDescription(const RequestType & request) const;
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/sdclib/src/SDCLib/Data/SDC/SDCConsumerAdapter.cpp:551:120: error: specialization of ‘template<class RequestType> Poco::URI SDCLib::Data::SDC::SDCConsumerAdapter::getRequestURIFromDeviceDescription(const RequestType&) const’ in different namespace [-fpermissive]
 Poco::URI SDCConsumerAdapter::getRequestURIFromDeviceDescription(const OSELib::SDC::SetContextStateTraits::Request & ) const {
                                                                                                                        ^~~~~
In file included from /home/user/sdclib/src/SDCLib/Data/SDC/SDCConsumerAdapter.cpp:8:0:
/home/user/sdclib/include/SDCLib/Data/SDC/SDCConsumerAdapter.h:70:12: error:   from definition of ‘template<class RequestType> Poco::URI SDCLib::Data::SDC::SDCConsumerAdapter::getRequestURIFromDeviceDescription(const RequestType&) const’ [-fpermissive]
  Poco::URI getRequestURIFromDeviceDescription(const RequestType & request) const;
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/CMakeFiles/SDCLib.dir/build.make:3230: die Regel für Ziel „src/CMakeFiles/SDCLib.dir/SDCLib/Data/SDC/SDCConsumerAdapter.cpp.o“ scheiterte
make[2]: *** [src/CMakeFiles/SDCLib.dir/SDCLib/Data/SDC/SDCConsumerAdapter.cpp.o] Fehler 1
CMakeFiles/Makefile2:486: die Regel für Ziel „src/CMakeFiles/SDCLib.dir/all“ scheiterte
make[1]: *** [src/CMakeFiles/SDCLib.dir/all] Fehler 2
Makefile:149: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

**Comment by FBaumeister** [comment]
Hello dmeise, thank you for reporting this issue. Unfortunately I could not reproduce your it on my system. Could you provide some additional system information so I can track it down?

Like:
uname -r
lsb_release -a
g++ --version
cmake --version

Thank you!

**Comment by dmeise** [comment]
Hello,
see system information below. 
I tried again to build version V4.3.3 after checking it out of GIT. This is still working, build without any failures.

`user@debian:~$ uname -r
4.9.0-9-amd64
user@debian:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch
user@debian:~$ g++ --version
g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

user@debian:~$ cmake --version 
cmake version 3.7.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
`

**Comment by FBaumeister** [comment]
Hello dmeise, I was able to reproduce your issue under g++ 6.3.0. and pushed a fix. If this solves it for you too, please let me know and mark this as solved.
Thank you again for reporting!

Edit: Sorry, my commit auto closed this issue. Reopened.

**Comment by dmeise** [comment]
My problem is solved. Building process is finishing without error.
