### ISSUE TITLE
Unable to access getMdState

### ISSUE THREAD

**Issue by Contributer123** [surgitaix/sdclib#6]
Data::SDC::SDCConsumer & consumer = *c;
**consumer.getMdState();**

will generate the error
**invalid use of incomplete type ‘class SDCLib::Data::SDC::MdState’**

**Comment by FBaumeister** [comment]
Hello dernako,
getMdState returns an instance of MdState.
You have to include
#include "SDCLib/Data/SDC/MDIB/MdState.h"

Edit:
I added MdState.h and MdDescription.h to SDCConsumer.h as this Header file should be self-sufficient.

Thank you for reporting this issue!
