### ISSUE TITLE
CMakeExample

### ISSUE THREAD

**Issue by chimneywindow** [surgitaix/sdclib#8]
Hi,
I have difficulty with using the FindSDCLib.cmake/CMakeExample

I created the projectstructure described in `sdclib/Examples/CMakeExample/CMakeLists.txt` line 99...
and I did the out of source build to `dependencies/sdclib_build`.

I copied the CMakeLists.txt from `Examples/CMakeExample/` in my project root directory and 
the file from `Examples/CMakeExample/code` in my `src/` folder.

In CMakeLists.txt changed some paths: 
line 13:
`get_filename_component(PROJECT_CMAKE_MODULES ${CMAKE_CURRENT_LIST_DIR}/../../cmake/Modules REALPATH)`
`get_filename_component(PROJECT_CMAKE_MODULES ${CMAKE_CURRENT_LIST_DIR}/dependencies/sdclib/cmake/Modules REALPATH)`

line 111:
`get_filename_component(PATH_DEPS_ROOT ${CMAKE_CURRENT_LIST_DIR}/../../../ REALPATH)`
`get_filename_component(PATH_DEPS_ROOT ${CMAKE_CURRENT_LIST_DIR}/dependencies REALPATH)`

line 130:
`include$ (${SDCLib_SEARCH_DIRS}/FindSDCLib.cmake)`
`include(${SDCLib_SEARCH_DIRS}/cmake/Modules/FindSDCLib.cmake)`

line 153:
`add_subdirectory(code)`
`add_subdirectory(src)`

After `cmake .` in my project root folder and `make -j5`
I get "No rule to make target 'bin/libSDCLib_d.so' needed by 'bin/Dumm2_d' Stop."
Same for Dummy1, ExampleProvider

Already ´cmake .´ said "Could not find /home/user/lightcontrol/bin/libSDCLib_d.so)...
Can you help what I did/configure wrong?

**Comment by FBaumeister** [comment]
Hello chimneywindow.
Thank you for trying out the CMakeExample and reporting the issue.
I could not fully reproduce your error messages but I tried to setup your project structure.
The Example and Findscript did not work well with in source builds of your final project (cmake .) and out of source built sdclib (your first step, built in sdclib_build).

The major problem: The "Find"SDCLib script does more than just "finding" the SDCLib but gathering all resources for building the Lib too (Poco, Xerces etc.).

Let me recap:
- You made an out of source build of the sdclib in sdclib_build (worked).
- Setup your project according to the folder structure
- copied the code folder
- made an in source build and got the errors?

I applied some changes and pushed them. Can you try out the latest master commit?
The CMakeExample/CMakeLists.txt got some small changes as well. By setting the following value:
# set(SDCLib_EXTERNAL_LIBRARY_DIRS ${PATH_DEPS_ROOT}/sdclib_build/bin)
you override the SDCLib Binaries folder the "FindScript" will use.

**Comment by chimneywindow** [comment]
Yes, your steps are correct.

Now, I can make successful an in-source build of my project
after comment in `set(SDCLib_EXTERNAL_LIBRARY_DIRS` `${PATH_DEPS_ROOT}/sdclib_build/bin)`

in the CMakeExample/CMakeLists.txt.
Thank you for your fast repsonse!

For my lack of knowledge... if you are writing "The Example and Findscript did not work well with in source builds of your final project (cmake .) and out of source built sdclib (your first step, built in sdclib_build)."
Is it recommended to perform an in-source build for the sdclib if I use the FindSDCLib.cmake?

**Comment by FBaumeister** [comment]
The FindSDCLib script gathers all external dependencies to build the SDCLib including Poco, Xerces OpenSSL.
Strictly speaking this is not what a Find<NAME>.cmake script should be used for when you call it via find_package(<NAME>).
But it grew to a "convenience feature" to use the SDCLib with CMake without further knowledge on target linking on the dependencies into your own project.
We are aware of that design flaw and it is marked to change in future versions for a cleaner workflow.

Regarding your question:
I personally always recommend out-of-source builds with CMake in general.
When you manage your code with a version-control system you dont pollute your code base with the generated files and you can easily build and test different configurations ( f.e. debug / release).

**Comment by chimneywindow** [comment]
Okay, I understand the issues, thank you for your fast and detailed response!
